name: Algolia Upload Records

on:
  - push

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: test the action
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: ./
        with:
          algolia_api_key: ${{ secrets.API_KEY }}
          algolia_application_id: ${{ secrets.APPLICATION_ID }}
          # needs to be inside $GITHUB_WORKSPACE from actions/checkout step
          file: config.example.json
